### PR TITLE
Change method name 'display' to 'printUsage'

### PR DESCRIPTION
**Pull request by pdhung3012**
This class is used to represent InvalidCommandException.  This method named 'display' is to print usage. Thus, the method name 'printUsage' is more intuitive than 'display'.

### CODE REVIEW

**Comment by doubleblinddoubleblinddoubleblind** [comment]
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fcaliper%2Fpull%2F419) for more info**.

@googlebot I consent

**Comment by pdhung3012** [comment]
@googlebot I consent

**Comment by doubleblinddoubleblinddoubleblind** [comment]
@googlebot I consent.

**Comment by netdpb** [comment]
The method `display(PrintWriter)` is actually meant to display (or print) the user's error. It _also_ shows the usage string (by calling `displayUsage(PrintWriter)`). The methods could use better (or any) Javadoc.

I'm not sure how important it is to change "display" to "print".

Closing for now; feel free to reopen if I've misunderstood something.

**Pull request closed without merging**
